# Generated by Django 3.1.4 on 2023-01-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0002_auto_20230112_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
