# Generated by Django 3.1.4 on 2023-01-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0003_auto_20230112_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vehicle',
            field=models.CharField(choices=[('VAN', 'Van'), ('BICYCLE', 'Bicycle')], default='Van', max_length=50),
        ),
    ]
