# Generated by Django 3.1.4 on 2023-01-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0004_employee_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('VAN', 'Van'), ('BICYCLE', 'Bicycle')], default='', max_length=50),
        ),
    ]
