# Generated by Django 3.1.4 on 2023-01-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0008_auto_20230115_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
