# Generated by Django 3.1.4 on 2023-01-17 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DD', '0010_auto_20230116_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('order_id', models.IntegerField(default=50, primary_key=True, serialize=False)),
                ('expected_delivery_datetime', models.DateTimeField(auto_now=True)),
                ('actual_delivery_datetime', models.DateTimeField(auto_now=True)),
                ('cost_in_cents', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='timeframes',
        ),
        migrations.AddField(
            model_name='customer',
            name='available_days',
            field=models.CharField(default='Monday', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='available_parts_days',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], default='Morning', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Groningen', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Netherlands', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_and_number',
            field=models.CharField(default='Nothing', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(default='1111', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='delivered_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_deliverer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='is_breakable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='send_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='x_in_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='package',
            name='y_in_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='package',
            name='z_in_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('IN_DELIV', 'In delivery'), ('DELIV_FAIL', 'Delivery failed'), ('IN_WH', 'In warehouse')], default='IN_WH', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='last_delivery',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_delivery', to='DD.delivery'),
        ),
    ]
