# Generated by Django 3.1.4 on 2023-01-17 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DD', '0011_auto_20230117_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_deliverer', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='package',
            name='last_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_delivery', to='DD.delivery'),
        ),
    ]
