# Generated by Django 3.1.4 on 2023-01-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0011_auto_20230116_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('IN_DELIV', 'In delivery'), ('DELIV_FAIL', 'Delivery failed'), ('IN_WH', 'In warehouse')], default='IN_WH', max_length=255),
        ),
    ]
