# Generated by Django 3.1.4 on 2023-01-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0012_auto_20230116_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='available_days',
            field=models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='available_parts_days',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
