# Generated by Django 3.1.4 on 2023-01-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0013_auto_20230116_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='timeframes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='available_days',
        ),
        migrations.AddField(
            model_name='customer',
            name='available_days',
            field=models.ManyToManyField(to='DD.Available_days'),
        ),
    ]
