# Generated by Django 3.1.4 on 2023-01-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0014_auto_20230117_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='available_days',
        ),
        migrations.AddField(
            model_name='customer',
            name='available_days',
            field=models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
