# Generated by Django 3.1.4 on 2023-01-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DD', '0015_auto_20230117_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='available_days',
            field=models.CharField(max_length=50),
        ),
    ]
